api:
  image: rasca0027/ip2nation:v1
  volumes:
    - /home/rasca/Documents/tagtoo/ip2nation/iptonation/ip:/home/ 
  working_dir: /home/
  command: python manage.py runserver
  ports: "8000:8000"
  links:
    - mysql
mysql:
  image: rasca0027/mysql:v1
  volumes:
    - /home/rasca/Documents/tagtoo/ip2nation/:/home/
  working_dir: /home/
  command: /bin/bash ./mysql.sh 
